### ISSUE TITLE
Interface with git: being able to get latest commit information.

### ISSUE THREAD

**Issue by chrisparnin** [rchakra3/wolf#10]
- Look through getting with github api.
- Look with git itself (`git log`)
- Look at language wrappers.

**Comment by chrisparnin** [comment]
Some issues to think about? How do you get a "Java class from a changed file".

**Comment by rohancme** [comment]
Note: Java 8 has some new features which a lot of the existing parsers don't seem to handle. I'm unsure if the parsers would break with Any code written with Java 8 features or only specific features.

**Comment by chrisparnin** [comment]
Yes. I'm pretty sure that you'll find that "research tools" will greatly lag behind the most current version of a language. See if you can keep things at Java 7 if this becomes too much of an issue.

**Comment by rohancme** [comment]
Yes I think for now I'll guarantee compatibility only with Java 7 and see how things go.  I've got a simple parser implemented with the last commit (https://github.com/rchakra3/wolf/commit/3dc6343203ac6740e68693eb016b8385d0f1e929). 

Thinking of using [GitPython](https://gitpython.readthedocs.org) for information about the latest commit in the given repo. I'll probably have a command line argument to specify how many of the previous commits should be taken into consideration

**Comment by rohancme** [comment]
See #13 for functionality updates

**Comment by chrisparnin** [comment]
Right now using gitpython to handle git commits.
