### ISSUE TITLE
Fix gitpython env and shutils pip problems 

### ISSUE THREAD

**Issue by chrisparnin** [rchakra3/wolf#14]
It worked when I manually installed via `pip install gitpython`

**Comment by rohancme** [comment]
Managed to reproduce this on a mac today. Will investigate.

Issue does not seem to appear on Ubuntu 12/14/15

**Comment by rohancme** [comment]
Solved with @mrajashree's PR #22 . It was an issue caused by the absence of certain other dependencies.
