### ISSUE TITLE
Explore integration with PITest

### ISSUE THREAD

**Issue by chrisparnin** [rchakra3/wolf#18]
- Can PITest run on just a class/namespace? Does it run on everything?
- Is the program accessible report?
- GOAL: Of your generated tests (which means you need to keep track of yours), be able to get the status of "NO COVERAGE, FAIL, PASS" for each test.
- What about existing test suite? Is your results in line with the manual created one? Say, 70% had PASS. Does your generated tests have similar ratio? What is the typical coverage ratio for mutation testing coverage?

**Comment by rchakra3** [comment]
@chrisparnin . Well it looks like Randoop isn't really doing anything useful on the Rome repo after a certain point. There's no increase in either line or mutation coverage after the first set of generated tests. Randoop generates test classes with 300-500 tests in each class. These are the results I got by working at the class level. I'm sure if I went down to the individual test level, these numbers could be reduced further.

Both promising (in terms of being able to cut down the number of tests) and disappointing (in terms of Randoop's contribution to line/mutation coverage improvement):

#### **Here's the line + mutation coverage report before adding the randoop tests:**

![rome_io_before](https://cloud.githubusercontent.com/assets/2264912/13306169/54d2d296-db2f-11e5-817f-cbb96bfeda1a.png)

<br>
<br>

#### **After adding ~500 of the randoop tests [Line up by 5% and Mutation up by 6%]**

![rome_io_after_reduction](https://cloud.githubusercontent.com/assets/2264912/13306345/d4534180-db30-11e5-9f2e-4110fe936d5d.png)

<br>
<br>
#### **After adding the remaining tests. Bringing the total to ~12000 [No change whatsover]:**

![rome_io_after](https://cloud.githubusercontent.com/assets/2264912/13306360/ed8d014a-db30-11e5-8e27-46d30fa0aded.png)

**Comment by rohancme** [comment]
- PITest can be configured to run for a particular namespace regex only. I currently find the longest common package name prefix and use this.
- Randoop generated tests are primarily RegressionTests, which means they all pass
